### ISSUE TITLE
Copy suggestions for /network

### ISSUE THREAD

**Issue by sohkai** [aragon/website#19]
> Putting the power back into the hands of ~~the~~ users

> The Aragon Network will decentralize its governance by gradually handing over control of the project to ~~the~~ **its** users

> The Aragon Network will establish additional services for ~~the~~ organizations taking advantage of what Aragon Core provides

^ Begs the question, what does Aragon Core provide? Maybe we could substitute a description the value add instead? Or would it be better to say "organizations backed by Aragon Core"?

> Our mission is to make the Aragon Network an autonomous organization ~~itself, which~~ **that** is managed by the people using it for their mutual prosperity

> IMAGINE A NATION WITHOUT LAND ~~AND~~ **OR** BORDERS

> The Aragon Network Token, ANT, puts the power into the hands of the ~~people participating in the operation~~ **participants** of the Network. Every single aspect of the Network will be governed **only** by those willing to make an effort for a better future

> Aragon Governance Proposals ~~is a system~~ **are a way** for community members to join the discussion and create proposals affecting Aragon

> Everyone is welcome to ~~join in and aid in forging~~ **help forge** the future of ~~how~~ Aragon ~~will shape out to be~~. Together **,** we can build the exciting future ~~which~~ we want

#### Consider rewording:
> Aragon Network will be the first community governed decentralized organization whose goal is to act as a digital jurisdiction, an online decentralized court system that isn’t bound by traditional artificial barriers such as national jurisdictions or the borders of a single country

to 

> The Aragon Network will be the first community governed, decentralized organization whose goal is to act as a digital jurisdiction: an online, decentralized court system free from the traditional artificial barriers of national borders and jurisdictions

#### Consider rewording:

> Aragon organizations can be upgraded seamlessly using our AragonOS architecture. They can solve disputes between two parties by using the decentralized court system, a digital jurisdiction that operates only online and utilizes your peers to resolve issues

to

> Aragon organizations will be upgraded seamlessly by running on AragonOS. Disputes between two parties will be solved through the decentralized court system by utilizing your peers to resolve issues

**Comment by Smokyish** [comment]
@sohkai 
> ^ Begs the question, what does Aragon Core provide? Maybe we could substitute a description the value add instead? Or would it be better to say "organizations backed by Aragon Core"?

That should hopefully be apparant in the Core page :)

> Our mission is to make the Aragon Network an autonomous organization ~~itself, which~~ **that** is managed by the people using it for their mutual prosperity

This is meant to help make it clear that we want to have thousands of DAOs, AN being one of them, not just a network like so many other projects which are calling themselves networks.

> IMAGINE A NATION WITHOUT LAND ~~AND~~ **OR** BORDERS

This is supposed to be like a mental image, close your eyes and imagine a nation that has no land and no borders. And or would imply that there is possibility of the other one existing and we want to bring about the idea of a nation without either.

> The Aragon Network Token, ANT, puts the power into the hands of the ~~people participating in the operation~~ **participants** of the Network. Every single aspect of the Network will be governed **only** by those willing to make an effort for a better future

The word only was there originally but @john-light who was the native English speaker proof reading the text felt it was unnecessary. (He also okayed the other sentences in their current form)

> Aragon Governance Proposals ~~is a system~~ **are a way** for community members to join the discussion and create proposals affecting Aragon

I think it's more of a system, and it is our main way for anyone, team or community member, to create a proposal. A way would imply that there are other ways, and we want to keep the governance proposals focused on this one place.

> Everyone is welcome to ~~join in and aid in forging~~ **help forge** the future of ~~how~~ Aragon ~~will shape out to be~~. Together **,** we can build the exciting future ~~which~~ we want

I think joining gives the sense of becoming a part of something and that's why it was used. Also we don't know what shape or form Aragon will take in the future, thus this wording :)

> The Aragon Network will be the first community governed, decentralized organization whose goal is to act as a digital jurisdiction: an online, decentralized court system free from the traditional artificial barriers of national borders and jurisdictions

The network might not actually be free from those barriers, but it is not bound by them, and this is to give an example of things like national jurisdictions and borders of a single country that are currently restricting your freedom to act as you'd wish in a global environment.

> Aragon organizations will be upgraded seamlessly by running on AragonOS. Disputes between two parties will be solved through the decentralized court system by utilizing your peers to resolve issues

They won't be upgraded necessarily, they are given the option to have upgradeability.
