### ISSUE TITLE
Copy suggestions for /join

### ISSUE THREAD

**Issue by sohkai** [aragon/website#22]
> We are building the future of organizations

Maybe just "Build the future of organizations"? Or "Help build the future of organizations"?

> We do focused **,** deep work sessions **four** days a week, leaving Monday for meetings and calls

> Our position is product first **—** we place innovation and user experience above all else

#### Consider rewording:
> We don't necessarily work 9-5; getting the work done, meeting goals and milestones is more important.

to 

> We don't necessarily work 9-5; we work to meet goals and milestones.

#### Consider rewording:
> Working remotely and autonomously, having a positive and proactive attitude with a love for time self-management is essential to our day-to-day operations

to

> Working remotely and autonomously, you should have a positive and proactive attitude, with a love for time self-management

**Comment by Smokyish** [comment]
@sohkai 
> Maybe just "Build the future of organizations"? Or "Help build the future of organizations"?

The We is there because this is a "Join us" page, so it's meant to give the idea of what we're doing.

> We do focused **,** deep work sessions **four** days a week, leaving Monday for meetings and calls

Changing this to four added another line and made it inconsistent with the Fully distributed text on the same horizontal level :/

> We don't necessarily work 9-5; we work to meet goals and milestones.

This is also mostly a case of having a consistent text length on the different parts, but also to show that you're free to work as you want, somethings are more important than others, like working at a certain time.

> Working remotely and autonomously, you should have a positive and proactive attitude, with a love for time self-management

Also makes the text shorter and removes the key part of this being an essential part of what we do every day.
