### ISSUE TITLE
How to publish for production

### ISSUE THREAD

**Issue by luisivan** [aragon/website#37]
What's the best way? It is automatic once there's a push to `master`?

**Comment by bpierre** [comment]
There is this npm script: https://github.com/aragon/website/blob/master/package.json#L12

It will build the website and push to the `gh-pages` branch, which is the one that is used in production. For this reason, we shouldn’t manually push commits to `gh-pages`, because the script would override them.

The normal way to publish in production is to run this command:

```sh
npm run deploy
```

**Comment by luisivan** [comment]
Awesome, thanks!
